### PR TITLE
Fix of #15

### PR DESCRIPTION
**Pull request by mmorel-35**
Fix for  #15 
The auto download need to be allowed explicitly by the api user.
When the file already exists a tmp and old files are created to shorten the time of indisponibility as much as possible.
I also added the commons-io  dependency

### CODE REVIEW

**Comment by ankushs92** [comment]
Quite hefty work, I thank you. I will review your changes as when I get time and get back to you. Expect a few days to a week.

**Comment by mmorel-35** [comment]
I'm glad to help, you're welcome.

**Comment by ankushs92** [comment]
Great. Thanks for all the work you've done. Maybe you could work on the ini file as well? Anyway, I along with [Paul](https://github.com/paulrutter) are trying to fix [this](https://github.com/ankushs92/Browscap4j/issues/19) issue first. Till this one is solved, it would not be possible for me to accept your pull requests yet. Maybe you can have a look at it ?

**Comment by mmorel-35** [comment]
Ok. I'm going to take a look on that. By the way, I created on my repo, two  new parsers for xml and json. I also discovered that the number of patterns wasn't the same between the different files.

**Comment by ankushs92** [comment]
Yea i know. That is one  of the reason why I only used the csv file because
it contains all patterns.

**Comment by mmorel-35** [comment]
It seem that the json file has more. Csv : 184010, xml 74792, json 191489

**Comment by ankushs92** [comment]
Oh ok. Back when I created the repo, the csv file had more entries. Also,
the larger the file, the more heap space it would need. I think that we
should also look into the possibility of allowing a user to chose the
browscap.ini file (the smallest file). Would make for a well rounded
library.

**Comment by mmorel-35** [comment]
Definitely! It seem that ini4j would be helpful for ini parsing. I also think that the remote URLs for version verification and download could be changed by the user so he can use his own services .

**Comment by ankushs92** [comment]
>  I also think that the remote URLs for version verification and download could be changed by the user so he can use his own services .

Didn't get you. Could you elaborate?

**Comment by mmorel-35** [comment]
For now the remote urls are the urls of browscap.org but someone might want to use others. So we can keep the browscap urls as default urls and  allow the user to use others if he has another service delivering the version and the files.

**Comment by mmorel-35** [comment]
I finally decided to use the previous version with the maps plus my implementation of the ini parsing service.

**Comment by ankushs92** [comment]
Previous implementation, as in? You mean with `parallelStreams` ?

**Comment by mmorel-35** [comment]
Exactly, I mean the implementation of the 1.4.4 version.

**Pull request closed without merging**
